---
logging:
  enabled: False
inventory:
  plugin: SimpleInventory
  options:
    host_file: "/home/pspycher/class5/hosts.yaml"
    group_file: "/home/pspycher/nornir_inventory/groups.yaml"
    defaults_file: "/home/pspycher/nornir_inventory/defaults.yaml"
